parameters:
#    vieille_sardine_panier.example.class: VieilleSardine\PanierBundle\Example

services:
#    vieille_sardine_panier.example:
#        class: %vieille_sardine_panier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
