<?php

namespace VieilleSardine\StockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CouloirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouloirRepository extends EntityRepository
{
}
