<?php

namespace VieilleSardine\StockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StockPhysiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockPhysiqueRepository extends EntityRepository
{
}
