security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_user_bundle:
            id: fos_user.user_provider.username_email
        
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    .*
            form_login:
                provider:           fos_user_bundle
                csrf_provider:      form.csrf_provider
                login_path:         fos_user_security_login
                check_path:         fos_user_security_check
                use_forward:        false
                failure_path:      null
                default_target_path:    /catalogue
            logout:
                path:                   fos_user_security_logout
                target:                 /catalogue
                invalidate_session:     false
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml
                path:       /
            anonymous:    true
