<?php

namespace VieilleSardine\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompteClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteClientRepository extends EntityRepository
{
}
