<?php

namespace VieilleSardine\LivraisonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonRepository extends EntityRepository
{
}
