<?php

namespace VieilleSardine\LivraisonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PreparateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreparateurRepository extends EntityRepository
{
}
