<?php

namespace VieilleSardine\PaiementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarteBancaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteBancaireRepository extends EntityRepository
{
}
