<?php

namespace VieilleSardine\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BonLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonLivraisonRepository extends EntityRepository
{
}
