<?php

namespace VieilleSardine\RetourBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RetourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetourRepository extends EntityRepository
{
}
